version: '3'

services:
  app:
    restart: always
    container_name: telegram-redirect-bot
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:80"